import {
  CONDUCTEUR_FEN,
  COURSES,
  CULTURE,
  DD,
  DECO,
  LOG_ELEC,
  FEN,
  HUMAIN,
  INFORMATIQUE,
  TEAM_25EME,
  TEAM_ELEC,
  ACCUEIL_ARTISTE,
  BAR,
  BARRIERES,
  BEBOO,
  BUREAU,
  CATERING,
  COMMUNICATION,
  CONCERT,
  LOG_MATOS,
  PAYANT,
  PLAIZIR,
  SCENE,
  SECU,
  SG,
  SIGNA,
  RSE,
  SPONSO,
  SPORTS,
  VIEUX,
} from "@overbookd/team-constants";

// Activities and tasks from 50th edition of the festival

export const oldActivities = new Map<string, number>([
  [TEAM_25EME, 2],
  [ACCUEIL_ARTISTE, 5],
  [BAR, 22],
  [BARRIERES, 2],
  [BEBOO, 7],
  [BUREAU, 2],
  [CATERING, 6],
  [COMMUNICATION, 5],
  [COURSES, 23],
  [CULTURE, 38],
  [DD, 12],
  [DECO, 28],
  [LOG_ELEC, 4],
  [HUMAIN, 1],
  [INFORMATIQUE, 1],
  [LOG_MATOS, 5],
  [PAYANT, 4],
  [PLAIZIR, 14],
  [RSE, 9],
  [SCENE, 9],
  [SECU, 13],
  [SIGNA, 10],
  [SPONSO, 14],
  [SPORTS, 28],
]);

export const oldTasks = new Map<string, number>([
  [TEAM_25EME, 2],
  [ACCUEIL_ARTISTE, 20],
  [BAR, 92],
  [BARRIERES, 32],
  [BEBOO, 13],
  [BUREAU, 20],
  [CATERING, 9],
  [COMMUNICATION, 26],
  [CONCERT, 28],
  [CONDUCTEUR_FEN, 4],
  ["coquette", 1],
  [COURSES, 71],
  [CULTURE, 77],
  [DD, 42],
  [DECO, 64],
  [LOG_ELEC, 72],
  [FEN, 1],
  [HUMAIN, 18],
  [INFORMATIQUE, 1],
  [LOG_MATOS, 70],
  [PAYANT, 13],
  [PLAIZIR, 40],
  [RSE, 37],
  [SCENE, 47],
  [SECU, 111],
  [SG, 2],
  [SIGNA, 27],
  [SPONSO, 39],
  [SPORTS, 72],
  [TEAM_ELEC, 7],
  [VIEUX, 2],
]);
