// Activities and tasks from 50th edition of the festival

export const oldActivities = new Map<string, number>([
  ["25eme", 2],
  ["accueil-artiste", 5],
  ["bar", 22],
  ["barrieres", 2],
  ["beboo", 7],
  ["bureau", 2],
  ["catering", 6],
  ["communication", 5],
  ["courses", 23],
  ["culture", 38],
  ["dd", 12],
  ["deco", 28],
  ["elec", 4],
  ["humain", 1],
  ["informatique", 1],
  ["matos", 5],
  ["payant", 4],
  ["plaizir", 14],
  ["rse", 9],
  ["scene", 9],
  ["secu", 13],
  ["signa", 10],
  ["sponso", 14],
  ["sports", 28],
]);

export const oldTasks = new Map<string, number>([
  ["25eme", 2],
  ["accueil-artiste", 20],
  ["bar", 92],
  ["barrieres", 32],
  ["beboo", 13],
  ["bureau", 20],
  ["catering", 9],
  ["communication", 26],
  ["concert", 28],
  ["conducteur-fen", 4],
  ["coquette", 1],
  ["courses", 71],
  ["culture", 77],
  ["dd", 42],
  ["deco", 64],
  ["elec", 72],
  ["fen", 1],
  ["humain", 18],
  ["informatique", 1],
  ["matos", 70],
  ["payant", 13],
  ["plaizir", 40],
  ["rse", 37],
  ["scene", 47],
  ["secu", 111],
  ["sg", 2],
  ["signa", 27],
  ["sponso", 39],
  ["sports", 72],
  ["team-elec", 7],
  ["vieux", 2],
]);
