FROM node:16-alpine

WORKDIR /overbookd

RUN npm install -g pnpm
RUN pnpm --version
COPY pnpm-lock.yaml ./

RUN pnpm fetch

ADD ./ ./
RUN pnpm install -r --offline --filter '@overbookd/web'

WORKDIR /overbookd/apps/web

ENV HOST=0.0.0.0

EXPOSE 1234

CMD ["sh", "-c", "NUXT_TELEMETRY_DISABLED=1 pnpm --filter '@overbookd/web' run dev"]