export const gears = [
  'Parasol',
  'Caisse Gobelets bleue',
  'Demis générique 33cl',
  'Pintes 46e ',
  'Pintes Générique 55cl',
  'Europalette',
  'Micro-onde',
  'Assiettes céramique',
  'Spülboy',
  'Prolongateur 20m (3P+N+T) 32A',
  'Prolongateur 30m (3P+N+T) 32A',
  'Reglette néon 1200mm',
  'Reglette néon 650mm',
  'Matelas',
  'Projecteur Quartz 500w (a réparer)',
  'Elingues',
  'Tube LED RGB 1M',
  'Rouleau fil rigide Vert/Jaune 1.5',
  'Fouet 32 AT -> 3x 32 mono',
  'Crochet projecteur ',
  'Guirlande 17m',
  'Guirlande 29m',
  'Guirlande 11.5m',
  'Guirlande 5 m',
  'Guirlande 13m',
  'Guirlande 6m',
  'Guirlande 24 m',
  'Guirlande 19 m',
  'PC 16A F Etanche',
  'PC 16A F non étanche',
  'PC 16A M non étanche',
  '3G 1.5 rouleau 30m H07',
  '3G 0,75 souple, rouleau~15m',
  'PAR 56',
  'AMPOULE PAR 64 MFL',
  'Projecteur LED',
  'Kit Câblage + controleur LED',
  'Prise mâle 32 AT',
  'Caisse ampoule 100W',
  'Ampoule LED',
  'Ampoule HIT400',
  'Ampoule quartz 1000W',
  'Ampoule quartz 500W',
  'Ampoule quartz 300W',
  'Ampoule quartz 100 W',
  'Planche 95*25 L=1,2',
  'Mendrilles L=0,9',
  'Planche 130*15 L=0,5',
  'Planche 195*20 L=1',
  'Planche 280*10 L=0,7',
  'Agglo 40*30 ep 1 cm',
  'Agglo 80*30 ep 1 cm',
  'Lamelé collé477*20 L=1,25',
  'Tasseaux22*20 L=2,4m',
  'Planche 300*18 L=1,5m',
  'Maxi chevre 120*120 L=1,5m',
  'Lamboure 93*55 L=1,2m',
  'Ph de paintes rouge L=1,8, 50 large ep 2,8 cm',
  'Ph de paintes rouge L=1,25 50 large ep 2,6 cm',
  'Pied à coulisse jaune',
  'Percolateur',
  'Grand Thermos',
  'Machine à café',
  'Bac gastro 1/1 150mm',
  'Bac gastro moyen',
  'Bac gastro petit profond',
  'Marmite',
  'Flûtes',
  'Seau alimentaire',
  'Carafe à vin',
  '100W',
  'Projecteur 500W-bis',
  'Projecteur 300W bis',
  'Projecteur 100W',
  'Projecteur LED BIS',
  'Nappe papier verte (en m)',
  'Nappe papier mauve (en m)',
  'Toile 1.5*20m noire',
  'Toile 1.5*10 blanche',
  'Toile Tissu 18*20m',
  'Pinces à linge neuves',
  'Gants nitrile',
  'Liquide vaisselle (en L)',
  'Savon mains neuf (500mL)',
  'Sac poubelle très gros',
  'Panneau rassemblement',
  'Mur 5x8 (2x5 m)',
  'Mur 5x8 fenêtre (2x2 m)',
  'Mur 6x14 fenêtre (2x2 m)',
  'Mur 6x14 (2x6 m)',
  'Mur fenêtre (8x2 m)',
  'Mur fenêtre (2x2 m)',
  'Mur 3x3 (3x2 m)',
  'Mur 4x4 (4x2 m)',
  'Mur scène roots (10x2 m)',
  'Mur (3x2,5 m)',
  'Pied enceinte/parasol (lourd)',
  'Médailles courses (office des sports)',
  'Coupe course (grande)',
  'Coupe course (moyenne)',
  'Coupe course (petite)',
  'Boîte Plexo carrée',
  'Percolateur 6,8L',
  'Percolateur 15L',
  'Cuillère inox',
  'Couteau inox',
  'Fourchettes inox',
  'Verre à eau',
  'Tasse à café',
  'Tasse 20cL',
  'Verre à pied',
  'Boîte plexo ronde',
  'Etagère en kit DOC INSA',
  'Bracelet 2 soirs 46e',
  'Lot de Kapla',
  'Assiette en carton',
  'Sac congelation',
  'Sucre (kg)',
  'Couteau plastique',
  'Cuillère plastique',
  'Fourchette plastique',
  'Gobelet en carton',
  'Touillettes',
  'Sucrette',
  'Bol en carton',
  'Bol en plastique',
  'Verre en plastique',
  'Sel (kg)',
  'Boule à thé inox',
  'Ecumoir (petit)',
  'Ecumoir (grand)',
  'Rouleau papier cuisson',
  'Minuteur',
  'Rouleau aluminium',
  'Cuisinière',
  'Caisse rangement',
  'Parcours aveugle',
  'Drap housse',
  'Alèse',
  'Corde à linge (28m)',
  'Heras',
  'Vauban',
  'Rouleau rubalise (m)',
  'Plot béton',
  'Tente 4,5x3m noire',
  'Tente 3x3m noire',
  'Tente 3x3m blanche',
  'Tente 4x4m blanche',
  'Tente 6x4m blanche',
  'Tente 6x3m blanche',
  'Barre de tente 4M',
  'Mur tente 3x3m blanc',
  'Mur tente 3x3m noir',
  'Mur tente 4x4m Blanc',
  'Mur tente 4,5x3m noir',
  'Compteuse à gobelets',
  'Bâche Toilette',
  'Coffret 32 AT',
  'Papier borne photo 1 boîte 400 images',
  'Toner black',
  'Cartouches ink cartridge black',
  'Cartouches ink cartridge jaune',
  'Cartouches ink cartridge cyan',
  'Cartouches ink cartridge magenta',
  'Jeux de cartes',
  'Caisse objets perdus',
  'Guinde statique ',
  'Tuyau arrosage',
  'Tuyau alim lave vaisselle / lave linge',
  'Raccord tuyau arrossage',
  'Haltère 8kg',
  'Sac à patate',
  'Bonnet de bains',
  'Serviette de bain',
  'Corde escalade 15m',
  'Ceintres',
  'Allèse jetable',
  'Support drapeau pliable',
  'Plots de sport',
  'Drinking roulette',
  'Papier brouillon',
  'Papier A3',
  'Rouleau papier',
  'Papier plan bleu',
  'Rouleau film plastique',
  'Cavaliers plastique',
  'Sac Poubelle biodégradable',
  'Torchon',
  'Tancarville',
  'Liquide parquet',
  'Sac Poubelle',
  'Caisse à pharmacie',
  'Rechange serpillère',
  'Eponges',
  'Gel hydroalcoolique (L)',
  'Pack de 75 lingettes désinfectante',
  'Spray nettoyant savon noir',
  'Recharge savon main 1L',
  'Rouleau de sopalin',
  'Bombe désodorisante',
  'Aspirateur',
  'Pelle + balayette',
  'Bague réparation tente',
  'Chaise',
  'Grille d exposition',
  'Table cours 1 personne',
  'Table de réception',
  'Tireuse V400',
  'Tireuse FS125',
  'Tireuse FS70',
  'Tireuse FS40',
  'Mange debout',
  'Sono + alim',
  'Table basse',
  'Micro',
  'Affiche jour',
  'Podium roulant orange',
  'Affiche nuit',
  'Pupitre dircom',
  'Table de cours 2 personnes',
  'Urinoir dirpat (4m)',
  'Bidon alimentaire 25L',
  'Assiette plastique',
  'Table bois cuisine',
  'Gilet jaune',
  'Podium 3 places ',
  'Lave-main 4 robinets',
  'Support lave-main',
  'Multiprise 3 prises',
  'Megaphone',
  'Multiprise 6 prises',
  'Plot chantier',
  'Pommeau arosage',
  'Robinet arrivée deau',
  'Biblette',
  'Sceau',
  'Corde drisse',
  'Ballon basket',
  'Chasuble',
  'Prolongateur (P+N+T) 16A  20m pool',
  'Cable XLR (10m)',
  'Prolongateur (P+N+T) 16A  10m pool',
  'Mixette avec prise jack',
  'Prolongateur (P+N+T) 16A  5m pool',
  'Prolongateur (P+N+T) 16A  3m pool',
  'Lino (m²)',
  'Podium 8x6m',
  'Cable jack',
  'Drap blanc',
  "Bouteilles d'eau",
  'Câble éthernet (20m)',
  'Ficelle chanvre (m)',
  'Cafetière 12 Tasses',
  'Bidon non alimentaire',
  'Pinceaux',
  'Bouilloire 2L',
  'Banc réception',
  'Enrouleur 3g1.5 20m',
  'Enrouleur 3g1.5 40m',
  'Cagette verte',
  'Transpalette électrique',
  'Transpalette',
  'Cadenas',
  'Caisse de monnaie',
  'Agrapheuse bureautique',
  'Tablette caisse',
  'Touret',
  'Agrapheuse bricolage',
  'Miroir sur pied',
  'Detergent sol',
  'Nettoyant à vitre',
  'Baby foot',
  'Cendrier',
  'Moquette (m²)',
  'Trousse de secours',
  'Tatami',
  'Vidéoprojecteur',
  'Jerricane gazoil',
  'Pompe à gazoil',
  'Ordinateur gigabyte',
  'Chaussures de sécu',
  'Casque de chantier',
  'Ecran ordinateur',
  'Caddie',
  'Balais',
  'Poliane (rouleau)',
  'Miroir',
  'Serpillère',
  'Distributeur gel hydroalcoolique',
  'Désinfectant multi-surface (750ml)',
  'Balais-serpillère',
  'Support gel hydroalcoolique',
  'Wii',
  'Filet badminton',
  'Cellophane noir',
  'Extincteur CO2',
  'Extincteur AFFF',
  'Plaque à induction',
  'Extincteur eau',
  'Imprimante laser N&B',
  'Imprimante couleur',
  'Materiel cirque AJIL',
  'Jeu de Mölkky',
  'Lestes',
  'Poubelle 4 roues (600L)',
  'Planche à repasser',
  'Nourisse 4 voies',
  'Melangeur 15/21',
  'Fer à repasser',
  'Terminal paiement partenaire',
  'Evier',
  'Raclette ',
  'Crepiere',
  'Raclette à vitre',
  'Baignoire',
  'Lingettes nettoyantes',
  'Chiffon',
  'Planche à découper',
  'Pintes 45e',
  'Pintes 44e',
  'Pintes génériques noir et blanc',
  'Marteau',
  'Pintes vielles éditions',
  'Pintes génériques couleur',
  'Mètre',
  'Décamètre',
  'Niveau à bulle',
  'Sac poubelle 50L',
  'Pince coupante',
  'Sac poubelle transparent 100L',
  'Sac poubelle 200L',
  'Thermos 2L',
  'Sac poubelle jaune transparent 100L',
  'Rubalise',
  'Nappe papier',
  'Louche',
  'Gaffeur blanc',
  'Clef plate Ø17',
  'Gaffeur noir',
  'Scotch papier',
  'Clef plate Ø19',
  'Gants manutention',
  'Fil de fer',
  'Cotton à gratter (m²)',
  'Masque chirurgical',
  'Fer à souder',
  'Jeu boules de pétanque',
  'Chaise de bureau',
  'Occultant Heras',
  'Boîte à chargeur',
  'Barbecue',
  'Panneau à clés',
  'Support de tri',
  'Câble HDMI 20m',
  'Bracelets 47',
  'Scanette Weezevent',
  'Guichet thermique Weezevent',
  'Routeur 4G Weezevent',
  'Mini golf - Obstacles',
  'Mini golf - Moquette',
  'Mini golf - Encadrements bois',
  'Mini golf - Encadrement canettes',
  'Clubs de golf',
  'Tente tubulaire 5x8m (tubes + toit)',
  'Tente tubulaire 6x14m (tubes +toit)',
  'Piano',
  'Cercleuse',
  'Pastilles Spülboy',
  'Chariot Beurk',
  'Prolongateur (P+N+T) 16A 100m',
  'Siège piano',
  'Cafe moulu (kg)',
  'Tente Berbère',
  'Ciseaux',
  'Entonnoir agrave (large diamètre)',
  'Couvercle marmitte',
  'Paravent',
  'Projecteur découpe',
  'Roue carte Dino',
  'Déco (voir avec la décom)',
  'Pic à brochette',
  'Tabouret de chez antonin & stoophe',
  'Porte tente 3x3m noir',
  'Gouttière souple 3m',
  'Grosse craies couleur (pot)',
  'Tenaille',
  'Pince Multiprise',
  'Clé à molette',
  'Porte embout',
  'Tournevis Cruciforme',
  'Tournevis Plat',
  'Cutter',
  'Paire de ciseaux',
  'Escabeau',
  'Pistolet à colle',
  'Visseuse/Perceuse',
  'Set embouts',
  'Set forets',
  'Scie sauteuse',
  'Scie à main',
  'Meuleuse ',
  'Lime',
  'Ponceuse',
  'Drisse (m)',
  'Barnier',
  'Econome',
  'Gaffer',
  'Fils de fer (m)',
  'Plateau de présentation',
  'Papier de verre',
  'Papier toilette',
  'Lestes vides à réparer',
  "Adhésif d'emballage 100m*50mm",
  'Passe câbles 1m',
  'Spikeball',
  'Bombe marquage',
  'Colson',
  'Clé de 19',
  'Câble électrique 3g0.75mm² (en m)',
  'Corbeille à papier noire',
  'leste pour parasols à remplir',
  'Tréteau',
  'Bac Gastro 1/1 65mm',
  'Couvercle gastro 1/1',
  'Trépied télescopique',
  'Agrafes pour cercleuse',
  'Ampoule halogène 42W ',
  'Guinguette (en mètres)',
  'PAR 64',
  'Ampoule sécu (1000W)',
  'Fil de cuivre (en mètres)',
  'Interrupteur poussoir',
  'Prises mâles PC16',
  'Prise femelle PC16',
  'Dominos (petits)',
  'Domino (gros)',
  'Domino (très gros)',
  'Domino (moyen)',
  'Gaine thermo rétractable',
  'Boîtier de dérivation (gros modèle)',
  'Interrupteur (qui tourne)',
  'Prise connexion 32 Tetra terre',
  'Coffret 32AT triphasé',
  'Tuyau d arrosage (en mètre)',
  'Boîtier de dérivation (petit format)',
  'Projecteurs LED',
  'Pichet',
  'Bain-marie',
  'Tote-bag logo 24',
  'Tubes halogen',
  'Recharges projecteurs (300, 150, 120 (x7), 1000 (x2 - douteux)',
  'Projecteur 120W',
  'Projecteur 500W',
  'Projecteur 300W',
  'Projecteur 400W',
  'Projecteur 1000W',
  'Projecteur 150W',
  'Marqueur',
  'Stylo bille',
  'Feuille A4',
  'Scotch marron',
  'Portique alu 2.40m h1.60m',
  'Pied pour portique alu',
  'Trépied jaune 120cm',
  'Rouleau attaches-canisse',
  'Multiprises 18 prises 2m',
  'Etagère en bois',
  'Porte tente 4x4 blanche',
  'Porte tente 3x3 noire',
  'Porte tente 4,5x3 noire',
  'bâche noire 2x3 mètres noire',
  'house pour mur de tente',
  'BAES',
  'Etagère',
  'Ampoule LED 1W',
  'Colliers Héras',
  'Totebag 24 heures',
  'Home trainer',
  'Cartons avec photos (Expo 46 bis)',
  'Ampoules basse consommation (34W-43W-LED)',
  'Pochette plastifiée',
  'Grands cure-dent (x100)',
  'Diable',
  'Sangle à cliquet',
  'Talkie walkie',
  'Clicker',
  'Telephone portable',
  'Scotch de bureau',
  'Clé pompier',
  'Plastifieuse',
  'Feuilles à plastifier',
  'Post-it',
  'Massicot',
  'Pont KLS',
  'Multiprise 4 prises',
  'Multiprise 5 prises',
  'Antivol Ordinateur',
  'Ballon foot',
  'Pompe portable',
  'Triplettes Écocups',
  'Planche à clous',
  'Vélo',
  'Lampe frontale',
  'Corde à noeuds (heras)',
  'Corde à noeuds (vauban)',
  'Pince à déchet',
  'Poubelle ronde 100L',
  'Bâche borne photo ',
  'Balai de cantonnier',
  'Grosse casserole',
  'Petite casserole',
  'Très grosse casserole',
  'Passoires',
  'Grande Poêle',
  'Petite Poêle',
  'Saladier métal',
  'Saladier verre',
  'Spatule',
  'Cuillère en bois',
  'Grand couteau cuisine',
  'Petit couteau de cuisine',
  'Couteau à pain',
  'Rape de cuisine',
  'Robot mixeur',
  'Presse-ail',
  'Grand Wok',
  'Très grande poêle',
  'Grand saladier',
  'Ouvre-boîte',
  'Essoreuse à salade',
  'Plateau Beurk',
  'Fouet en métal',
  'Echelle',
  'Chaine (petite longueur)',
  'Chaine (grande longeur)',
  'Spot LED de Nuts',
  'Lieur automatique fil de fer',
  'Coussin',
  "Bouchons d'oreilles",
  'Balai brosse',
  'Ruban (courses)',
  'Canapé',
  'Fauteuil',
  'Sandow (m)',
  'Enrouleur 3g2.5 25m',
  'Caisse manutention',
  'Pince leatherman',
  'Corbeille (récipient) propre ',
  'Sac cabas',
  "Paquet d'allume feu",
  'Nappe papier Blanc',
  'Ampoule  W',
  'Tube flexible F20-27 vers M15-21 de 1m',
  'tube flexible M20-27 vers F20-27 de 2m',
  'Badge avec pince-épingle',
  'réglette éclairage LED autonome 1m',
  'Câbles de démarrage',
  'Raccord rapide Gardena fonctionnel',
  'LOT tampon encre UV',
  'Fer à repasser ',
  'Lampe de bureau (sans ampoule)',
  "Savon d'hotel (artiste) (dose shampoing)",
  'savon solide artiste',
  'Téléphone fixe',
  'Flexible douche + douchette',
  'chaussure de sécu',
  'Préservatif (masculin + féminin)',
  'câbles éthernet ~100m',
  'Cônes de sport',
  'valise',
  'Etabli Pliant',
  'Papier peint (Vert Rouge Noir)',
  'Grande table du local',
  'Terminal de Paiement Electromique (TPE) (Pool des assos)',
  'Prolongateur (P+N+T) 16A  20m',
  'Prolongateur (P+N+T) 16A  15m',
  'Prolongateur (P+N+T) 16A  13.5m',
  'Prolongateur (P+N+T) 16A  10m',
  'Acétone (1L)',
  'Clé triangle bac tri',
  'Masse',
  'Massette',
  'Pioche',
  'Rateau',
  'Gros scotch barnier orange',
  'White spirit (1L)',
  'Scie circulaire',
  'Guirlande 50m',
  'Prolongateur (P+N+T) 16A 5m',
  'Prolongateur (P+N+T) 16A 3m',
  'Multiprise 8 prises onduleur',
];
