# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: apps/api/prisma/schema.puml
      - id: end-of-file-fixer
        exclude: apps/api/prisma/schema.puml
      - id: check-yaml
        exclude: pnpm-lock.yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            feat,
            fix,
            test,
            chore,
            docs,
            style,
            perf,
            refactor,
            ci,
            prefeat,
            alpha,
            revert,
          ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          [
            "--json",
            "--exclude-secrets",
            "(password|supersecret)",
            "--exclude-files",
            ".spec.ts$",
          ]
        exclude: pnpm-lock.yaml
