version: "3"

volumes:
  mysql_keycloak_database:
    driver: local
  mysql_project_a_database:
    driver: local

networks:
  net_keycloak: {}
  api: {}

services:
  db_keycloak:
    image: library/mysql
    restart: always
    volumes:
      - mysql_keycloak_database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    networks:
      - net_keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db_project_a:
    platform: linux/x86_64
    image: library/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: overbookd
      MYSQL_USER: overbookd
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - api

  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    volumes:
      - ./assets/json/realm-export.json:/tmp/realm-export.json
    networks:
      - net_keycloak
      - api
    depends_on:
      db_keycloak:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master"]
      interval: 30s
      timeout: 3s
      retries: 10

  api:
    build: .
    restart: always
    depends_on:
      db_project_a:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - 2424:2424
    networks:
      - api
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db_project_a
      DATABASE_PORT: 3306
