packages:
  - constants/**
  - domains/**
  - libraries/**
  - apps/**
  - utils/**
  - '!**/dist/**'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: true
