FROM node:16.13-alpine3.11

# Create app directory
WORKDIR /overbookd/backend

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY package*.json ./

COPY . .

EXPOSE 2424

CMD [ "npm", "run", "start:dev" ]
