FROM node:16.15-bullseye-slim

RUN apt update
RUN apt upgrade -y

RUN apt install git musl-dev -y

WORKDIR /overbookd/backend

COPY ./backend/package.json ./backend/package-lock.json ./

RUN npm install

COPY . /overbookd

EXPOSE 3000

CMD ["sh", "-c", "npm run start:dev"]
