resource_rules:
  merge_requests:
    rules:
      - name: find all merged dependabot MR and forbidden Scope::Web label
        conditions:
          state: opened
          forbidden_labels:
            - Scope::Web
          ruby: resource[:source_branch].match(/dependabot\/(npm_and_yarn|docker)\/web.*/)
        actions:
          labels:
            - Scope::Web


      - name: find all merged dependabot MR and forbidden Scope::Api label
        conditions:
          state: opened
          forbidden_labels:
            - Scope::Api
          ruby: resource[:source_branch].match(/dependabot\/(npm_and_yarn|docker)\/api.*/)
        actions:
          labels:
            - Scope::Api

      - name: find all merged dependabot MR and forbidden Scope::Libs label
        conditions:
          state: opened
          forbidden_labels:
            - Scope::Libs
          ruby: resource[:source_branch].match(/dependabot\/(npm_and_yarn|docker)\/libraries.*/)
        actions:
          labels:
            - Scope::Libs

      - name: find all merged dependabot MR and forbidden Scope::Domain label
        conditions:
          state: opened
          forbidden_labels:
            - Scope::Domain
          ruby: resource[:source_branch].match(/dependabot\/(npm_and_yarn|docker)\/domains.*/)
        actions:
          labels:
            - Scope::Domain
