version: "3"

services:
  traefik:
    image: traefik:v2.3
    restart: always
    command:
      # Docker config
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      # Entrypoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
       # SSL
      - "--certificatesresolvers.le.acme.email=dsi@24heures.org"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      # Enable Dashboard
      - "--api.dashboard=true"
#      - "--log.level=DEBUG"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /certificats/acme.json:/acme.json
    #      - ./passwd:/passwd
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.services.traefik.loadbalancer.server.port=888"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$mv/7eBGq$$blXoet7kdjDve702x5gLx/"

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --label-enable --interval 300 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS:
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL:
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL:

networks:
  traefik-public:
    external: true
