import { Team } from "@overbookd/team";
import * as teamCodes from "@overbookd/team-code";

export const teams: Team[] = [
  {
    name: "Admin",
    code: teamCodes.ADMIN,
    color: "#000000",
    icon: "mdi-eye-circle",
  },
  {
    name: "Accueil artiste",
    code: teamCodes.ACCUEIL_ARTISTE,
    color: "#A166F2",
    icon: "mdi-plane-train",
  },
  {
    name: "Bar",
    code: teamCodes.BAR,
    color: "#F9C80E",
    icon: "mdi-beer",
  },
  {
    name: "Bar bouffe",
    code: teamCodes.BAR_BOUFFE,
    color: "#FFEB00",
    icon: "mdi-french-fries",
  },
  {
    name: "Barrières",
    code: teamCodes.BARRIERES,
    color: "#F86624",
    icon: "mdi-boom-gate",
  },
  {
    name: "BDE",
    code: teamCodes.BDE,
    color: "#FF4343",
    icon: "mdi-bootstrap",
  },
  {
    name: "Bureau",
    code: teamCodes.BUREAU,
    color: "#e9c46a",
    icon: "mdi-desk",
  },
  {
    name: "Catering",
    code: teamCodes.CATERING,
    color: "#662E9B",
    icon: "mdi-food",
  },
  {
    name: "Camion",
    code: teamCodes.CAMION,
    color: "#737F49",
    icon: "mdi-truck-outline",
  },
  {
    name: "Communication",
    code: teamCodes.COMMUNICATION,
    color: "#262E9B",
    icon: "mdi-camera",
  },
  {
    name: "Concert",
    code: teamCodes.CONCERT,
    color: "#75d46c",
    icon: "mdi-microphone",
  },
  {
    name: "Conducteur",
    code: teamCodes.CONDUCTEUR,
    color: "#9B2E2E",
    icon: "mdi-car-key",
  },
  {
    name: "Conducteur FEN",
    code: teamCodes.CONDUCTEUR_FEN,
    color: "#9B2E2E",
    icon: "mdi-key-variant",
  },
  {
    name: "Confiance",
    code: teamCodes.CONFIANCE,
    color: "#d169e0",
    icon: "mdi-account-check",
  },
  {
    name: "Courses",
    code: teamCodes.COURSES,
    color: "#75d46c",
    icon: "mdi-bike-fast",
  },
  {
    name: "Culture",
    code: teamCodes.CULTURE,
    color: "#662E9B",
    icon: "mdi-theater",
  },
  {
    name: "DD",
    code: teamCodes.DD,
    color: "#32a852",
    icon: "mdi-tree",
  },
  {
    name: "Déco",
    code: teamCodes.DECO,
    color: "#662E9B",
    icon: "mdi-format-paint",
  },
  {
    name: "Elec",
    code: teamCodes.LOG_ELEC,
    color: "#ffb703",
    icon: "mdi-flash",
  },
  {
    name: "Fen",
    code: teamCodes.FEN,
    color: "#737F49",
    icon: "mdi-forklift",
  },
  {
    name: "Orga",
    code: teamCodes.HARD,
    color: "#969600",
    icon: "mdi-account-hard-hat",
  },
  {
    name: "Humain",
    code: teamCodes.HUMAIN,
    color: "#f4a261",
    icon: "mdi-human",
  },
  {
    name: "Informatique",
    code: teamCodes.INFORMATIQUE,
    color: "#3fd4af",
    icon: "mdi-monitor-screenshot",
  },
  {
    name: "Karna",
    code: teamCodes.KARNA,
    color: "#E4B613",
    icon: "mdi-party-popper",
  },
  {
    name: "Kfet",
    code: teamCodes.KFET,
    color: "#438EFF",
    icon: "mdi-beer",
  },
  {
    name: "BeBoo",
    code: teamCodes.BEBOO,
    color: "#ff66e8",
    icon: "mdi-human-female-boy",
  },
  {
    name: "Matos",
    code: teamCodes.LOG_MATOS,
    color: "#d4411e",
    icon: "mdi-truck",
  },
  {
    name: "CA",
    code: teamCodes.CA,
    color: "#e62727",
    icon: "mdi-account-hard-hat",
  },
  {
    name: "Payant",
    code: teamCodes.PAYANT,
    color: "#118C4F",
    icon: "mdi-ticket",
  },
  {
    name: "Plaizir",
    code: teamCodes.PLAIZIR,
    color: "#c9406a",
    icon: "mdi-ferris-wheel",
  },
  {
    name: "Scène",
    code: teamCodes.SCENE,
    color: "#EA3546",
    icon: "mdi-soundbar",
  },
  {
    name: "Sécu",
    code: teamCodes.SECU,
    color: "#e76f51",
    icon: "mdi-security",
  },
  {
    name: "SG",
    code: teamCodes.SG,
    color: "#ab1f07",
    icon: "mdi-human-male-child",
  },
  {
    name: "Signa",
    code: teamCodes.SIGNA,
    color: "#EA3546",
    icon: "mdi-sign-direction",
  },
  {
    name: "Bénévole",
    code: teamCodes.SOFT,
    color: "#2a9d8f",
    icon: "mdi-account-heart",
  },
  {
    name: "Sponso",
    code: teamCodes.SPONSO,
    color: "#50e691",
    icon: "mdi-cash",
  },
  {
    name: "Sports",
    code: teamCodes.SPORTS,
    color: "#a632b3",
    icon: "mdi-football",
  },
  {
    name: "Teckos",
    code: teamCodes.TECKOS,
    color: "#CFA602",
    icon: "mdi-hammer-wrench",
  },
  {
    name: "Hauts-de-France",
    code: teamCodes.HAUTS_DE_FRANCE,
    color: "#FF9300",
    icon: "mdi-unicorn",
  },
  {
    name: "Vieux",
    code: teamCodes.VIEUX,
    color: "#B5C2CB",
    icon: "mdi-human-cane",
  },
  {
    name: "Invité",
    code: teamCodes.INVITE,
    color: "#FF00AA",
    icon: "mdi-account-plus",
  },
  {
    name: "Voiture",
    code: teamCodes.VOITURE,
    color: "#737F49",
    icon: "mdi-car-side",
  },
  {
    name: "Personne",
    code: teamCodes.PERSONNE,
    color: "#09A1C4",
    icon: "mdi-account",
  },
  {
    name: "INSA Strasbourg",
    code: teamCodes.STRASBOURG,
    color: "#ACBB62",
    icon: "mdi-sausage",
  },
  {
    name: "INSA Centre Val de Loire",
    code: teamCodes.CVL,
    color: "#18CE5C",
    icon: "mdi-waves",
  },
  {
    name: "INSA Rouen",
    code: teamCodes.ROUEN,
    color: "#D6FF00",
    icon: "mdi-dolphin",
  },
];
