import { Team } from "../../src/team/team.model";

export const teams: Team[] = [
  {
    name: "Admin",
    code: "admin",
    color: "#000000",
    icon: "mdi-eye-circle",
  },
  {
    name: "Accueil artiste",
    code: "accueil-artiste",
    color: "#A166F2",
    icon: "mdi-plane-train",
  },
  {
    name: "Bar",
    code: "bar",
    color: "#F9C80E",
    icon: "mdi-beer",
  },
  {
    name: "Barrieres",
    code: "barrieres",
    color: "#F86624",
    icon: "mdi-boom-gate",
  },
  {
    name: "BDE",
    code: "bde",
    color: "#FF4343",
    icon: "mdi-bootstrap",
  },
  {
    name: "Bureau",
    code: "bureau",
    color: "#e9c46a",
    icon: "mdi-desk",
  },
  {
    name: "Catering",
    code: "catering",
    color: "#662E9B",
    icon: "mdi-food",
  },
  {
    name: "Camion",
    code: "camion",
    color: "#737F49",
    icon: "mdi-truck-outline",
  },
  {
    name: "Communication",
    code: "communication",
    color: "#262E9B",
    icon: "mdi-camera",
  },
  {
    name: "Concert",
    code: "concert",
    color: "#75d46c",
    icon: "mdi-microphone",
  },
  {
    name: "Conducteur",
    code: "conducteur",
    color: "#9B2E2E",
    icon: "mdi-car-key",
  },
  {
    name: "Conducteur FEN",
    code: "conducteur-fen",
    color: "#9B2E2E",
    icon: "mdi-key-variant",
  },
  {
    name: "Confiance",
    code: "confiance",
    color: "#d169e0",
    icon: "mdi-account-check",
  },
  {
    name: "Courses",
    code: "courses",
    color: "#75d46c",
    icon: "mdi-bike-fast",
  },
  {
    name: "Culture",
    code: "culture",
    color: "#662E9B",
    icon: "mdi-theater",
  },
  {
    name: "DD",
    code: "dd",
    color: "#32a852",
    icon: "mdi-tree",
  },
  {
    name: "Déco",
    code: "deco",
    color: "#662E9B",
    icon: "mdi-format-paint",
  },
  {
    name: "Elec",
    code: "elec",
    color: "#ffb703",
    icon: "mdi-flash",
  },
  {
    name: "Fen",
    code: "fen",
    color: "#737F49",
    icon: "mdi-forklift",
  },
  {
    name: "Hard",
    code: "hard",
    color: "#969600",
    icon: "mdi-account-hard-hat",
  },
  {
    name: "Humain",
    code: "humain",
    color: "#f4a261",
    icon: "mdi-human",
  },
  {
    name: "Informatique",
    code: "informatique",
    color: "#3fd4af",
    icon: "mdi-monitor-screenshot",
  },
  {
    name: "Karna",
    code: "karna",
    color: "#E4B613",
    icon: "mdi-party-popper",
  },
  {
    name: "Kfet",
    code: "kfet",
    color: "#438EFF",
    icon: "mdi-beer",
  },
  {
    name: "BeBoo",
    code: "beboo",
    color: "#ff66e8",
    icon: "mdi-human-female-boy",
  },
  {
    name: "Matos",
    code: "matos",
    color: "#d4411e",
    icon: "mdi-truck",
  },
  {
    name: "Orga",
    code: "orga",
    color: "#e62727",
    icon: "mdi-account-hard-hat",
  },
  {
    name: "Payant",
    code: "payant",
    color: "#118C4F",
    icon: "mdi-ticket",
  },
  {
    name: "Plaizir",
    code: "plaizir",
    color: "#c9406a",
    icon: "mdi-ferris-wheel",
  },
  {
    name: "Scène",
    code: "scene",
    color: "#EA3546",
    icon: "mdi-soundbar",
  },
  {
    name: "Sécu",
    code: "secu",
    color: "#e76f51",
    icon: "mdi-security",
  },
  {
    name: "SG",
    code: "sg",
    color: "#ab1f07",
    icon: "mdi-human-male-child",
  },
  {
    name: "Signa",
    code: "signa",
    color: "#EA3546",
    icon: "mdi-sign-direction",
  },
  {
    name: "Soft",
    code: "soft",
    color: "#2a9d8f",
    icon: "mdi-account-heart",
  },
  {
    name: "Sponso",
    code: "sponso",
    color: "#50e691",
    icon: "mdi-cash",
  },
  {
    name: "Sports",
    code: "sports",
    color: "#a632b3",
    icon: "mdi-football",
  },
  {
    name: "Teckos",
    code: "teckos",
    color: "#CFA602",
    icon: "mdi-hammer-wrench",
  },
  {
    name: "Tendrestival",
    code: "tendrestival",
    color: "#FF9300",
    icon: "mdi-balloon",
  },
  {
    name: "Vieux",
    code: "vieux",
    color: "#B5C2CB",
    icon: "mdi-human-cane",
  },
  {
    name: "Voiture",
    code: "voiture",
    color: "#737F49",
    icon: "mdi-car-side",
  },
  {
    name: "Woods",
    code: "woods",
    color: "#02AC18",
    icon: "mdi-forest",
  },
  {
    name: "Bénévole",
    code: "benevole",
    color: "#09A1C4",
    icon: "mdi-account",
  },
  {
    name: "INSA Strasbourg",
    code: "strasbourg",
    color: "#ACBB62",
    icon: "mdi-sausage",
  },
];
