import {
  HAVE_PERSONNAL_ACCOUNT,
  AFFECT_TEAM,
  BE_AFFECTED,
  WRITE_GEAR_CATALOG,
  READ_GEAR_CATALOG,
  READ_SIGNAGE_CATALOG,
  WRITE_SIGNAGE_CATALOG,
  WRITE_INVENTORY,
  MANAGE_PERSONNAL_ACCOUNTS,
  MANAGE_USERS,
  AFFECT_VOLUNTEER,
  MANAGE_CONFIG,
  MANAGE_LOCATION,
  VALIDATE_FA,
  VALIDATE_FT,
  READ_ANIMATION_TO_PUBLISH,
  READ_FA,
  WRITE_FA,
  READ_FT,
  WRITE_FT,
  VIEW_FESTIVAL_EVENTS_STATS,
  FILL_AVAILABILITY,
  VIEW_TIMELINE,
  ASK_FOR_HELP,
  VIEW_PLANNING,
  DOWNLOAD_PLANNING,
  ENROLL_NEWCOMER,
  VIEW_TROMBINOSCOPE,
  VIEW_VOLUNTEER,
  SEND_MAIL_TEST,
  MANAGE_PERMISSIONS,
  MANAGE_TEAMS,
  VIEW_DELETED_FT,
  VIEW_DELETED_FA,
} from "./permissions";

export type Permission =
  | typeof HAVE_PERSONNAL_ACCOUNT
  | typeof AFFECT_TEAM
  | typeof BE_AFFECTED
  | typeof WRITE_GEAR_CATALOG
  | typeof READ_GEAR_CATALOG
  | typeof READ_SIGNAGE_CATALOG
  | typeof WRITE_SIGNAGE_CATALOG
  | typeof WRITE_INVENTORY
  | typeof MANAGE_PERSONNAL_ACCOUNTS
  | typeof MANAGE_USERS
  | typeof AFFECT_VOLUNTEER
  | typeof MANAGE_CONFIG
  | typeof MANAGE_LOCATION
  | typeof VALIDATE_FA
  | typeof VALIDATE_FT
  | typeof READ_ANIMATION_TO_PUBLISH
  | typeof READ_FA
  | typeof WRITE_FA
  | typeof READ_FT
  | typeof WRITE_FT
  | typeof VIEW_FESTIVAL_EVENTS_STATS
  | typeof FILL_AVAILABILITY
  | typeof VIEW_TIMELINE
  | typeof ASK_FOR_HELP
  | typeof VIEW_PLANNING
  | typeof DOWNLOAD_PLANNING
  | typeof ENROLL_NEWCOMER
  | typeof VIEW_TROMBINOSCOPE
  | typeof VIEW_VOLUNTEER
  | typeof SEND_MAIL_TEST
  | typeof MANAGE_TEAMS
  | typeof MANAGE_PERMISSIONS
  | typeof VIEW_DELETED_FA
  | typeof VIEW_DELETED_FT;
