export const categoriesAndGears = [
  {
    name: 'BARRIERES',
    gears: ['Rouleau attache-canisses', 'Heras 3.5m', 'Vauban 2m'],
  },
  {
    name: 'ELEC',
    categories: [
      {
        name: 'ALIMENTATION',
        gears: [
          'Enrouleur 3g1.5 40m',
          'Coffret 32 AT',
          'Multiprise 3 prises',
          'Prolongateur (P+N+T) 16A 5m',
          'Prolongateur (P+N+T) 3G2.5 H07 16A 5m pool',
          'Fouet 32 AT -> 3x 32 mono',
          'Biblette',
          'Prolongateur (P+N+T) 16A 13.5m',
          'Prolongateur (P+N+T) 3G2.5 H07 16A 3m pool',
          'Prolongateur 20m (3P+N+T) 5G6 H07 32A',
          'Multiprise 5 prises',
          'Prolongateur (P+N+T) 16A 10m',
          'Multiprise 8 prises onduleur',
          'Multiprise 4 prises',
          'Prise mâle 32 AT',
          'Prolongateur (P+N+T) 3G2.5 H07 16A 10m pool',
          'Multiprises 18 prises 2m',
          'Prolongateur (P+N+T) 16A 3m',
          'Multiprise 6 prises',
          'Prolongateur (P+N+T) 16A 20m',
          'Prolongateur (P+N+T) 16A 15m',
          'Câble électrique 3g0.75mm² (en m)',
          'Prolongateur (P+N+T) 3G2.5 H07 16A 20m pool',
          'Prolongateur 30m (3P+N+T) 5G6 H07 32A',
        ],
      },
      {
        name: 'AUTRES',
        gears: [
          'Flycase',
          'Interrupteur poussoir',
          'Boîte plexo carrée',
          'Domino (très gros)',
          'Trépied télescopique',
          'Gaine thermo rétractable',
          'Boîte à chargeur',
          'Domino (moyen)',
          'Domino (gros)',
          'Boîtier de dérivation (gros modèle)',
          'Boîtier de dérivation (petit format)',
          'PC 16A F étanche',
          'Interrupteur (qui tourne)',
          'Trépied jaune 120cm',
          'Domino (petits)',
          'Elingue (sans maillon)',
          'Prise connexion 32 tetra terre',
          'Boîte plexo ronde',
          'Fil de cuivre (en mètres)',
          'Elingue',
          'PC 16A F non étanche',
          'PC 16A M non étanche',
          'Passe câbles 1m',
          'Câbles de démarrage',
        ],
      },
      {
        name: 'EAU',
        gears: [
          'Melangeur 15/21',
          'Lave-main 4 robinets',
          'Tuyau flexible douche + douchette',
          'Raccord tuyau arrossage',
          "Tuyau d'arrosage (en mètre)",
          'Tube flexible M20-27 vers F20-27 de 2m',
          'Tube flexible F20-27 vers M15-21 de 1m',
          'Raccord rapide Gardena',
          'Tuyau alim lave vaisselle / lave linge',
        ],
      },
      {
        name: 'ECLAIRAGE',
        gears: [
          'Crochet projecteur',
          'Guirlande 24 m',
          'PAR 64',
          'Ampoule PAR64 MFL',
          'Ampoule HIT400',
          'Projecteur 120W',
          'Guirlande 17m',
          'Projecteur 300W',
          'Ampoule sécu (1000W)',
          'Guirlande 6m',
          'Ampoule LED 1W',
          'Ampoule quartz 1000W',
          'Projecteur 1000W',
          'PAR 56 à reviser',
          'Projecteur 150W',
          'Projecteur 50W LED',
          'Ampoule LED',
          'Ampoule halogène 42W',
          'Réglette éclairage LED autonome 1m',
          'Guirlande 50m',
          'Tube halogene',
          'Guirlande 19 m',
          'Ampoule basse consommation (34W-43W-LED)',
          'Guirlande 13m',
          'Tube led RGB 1M',
          'Ampoule quartz 300W',
          'Reglette néon 1200mm',
          'Ampoule quartz 100 W',
          'Ampoule quartz 500W',
          'Lampe de bureau (sans ampoule)',
          'Projecteur 400W',
          'Reglette néon 650mm',
          'Kit câblage+ controleur LED',
          'Guirlande 11.5m',
          'Guirlande 29m',
        ],
      },
    ],
  },
  {
    name: 'MATOS',
    categories: [
      {
        name: 'AUTRES',
        gears: [
          'Jeu boules de pétanque',
          'Coupe course (moyenne)',
          'Bache sponso ninka 6x0,65',
          'Coupe course (grande)',
          'Parasol',
          'Ballon foot',
          'Serviette de bain',
          'Haltère 8kg',
          'Médailles courses (office des sports)',
          'Etagère en kit DOC INSA',
          'Banderole sponso KFC',
          'Planche à repasser',
          'Plot de sport',
          'Cône de sport',
          'Badge avec pince-épingle',
          'Portique alu 2.40m h1.60m',
          'Banderole sponso Ninka',
          'Clicker',
          'Etagère',
          'Corde escalade 15m',
          'Cintre',
          'Jeux de cartes',
          'Parcours aveugle',
          'Support drapeau pliable',
          'Peau de caisse claire',
          'Tote-bag logo 24',
          'Panneau à clés',
          'Roue carte Dino',
          'Leste pour parasols à remplir',
          'Drinking roulette',
          'Home trainer',
          'Pied pour portique alu',
          'Coupe course (petite)',
          'Peau de tom',
          'Cartons avec photos (Expo 46 bis)',
          'Valise',
          'Sac à patate',
          'Banderole sponso Radio Scoop rouge',
          'Fer à repasser',
          'Préservatif (masculin + féminin)',
          'Bonnet de bain',
          'Guinde statique',
          'Jeu de Mölkky',
          'Ruban (courses)',
        ],
      },
      {
        name: 'BARS',
        gears: [
          'Caisse de monnaie',
          'Pastilles Spülboy',
          'Pintes',
          'Compteuse à gobelets',
          'Triplette Écocups',
          'Ethylomètre électronique (sans embout)',
          'Spülboy',
          'Caisse gobelets bleue',
          'Tireuse FS40',
          'Demis générique 33cl',
        ],
      },
      {
        name: 'BUREAUTIQUE',
        gears: [
          'Post-it',
          'Papier borne photo 1 boîte 400 images',
          'Câble éthernet ~100m',
          'Câble éthernet (20m)',
          'Toner black',
          'Cartouche ink cartridge black',
          'Compteuse à pièces',
          'Papier plan bleu',
          'Corbeille à papier noire',
          'Câble HDMI 20m',
          'Antivol ordinateur',
          'Ordinateur gigabyte',
          'Cartouche ink cartridge jaune',
          'Cartouche ink cartridge magenta',
          'Papier A3',
          'Massicot',
          'Lot tampon encre UV',
          'Rouleau papier',
          'Papier brouillon',
          'Imprimante couleur',
          'Plastifieuse',
          'Ecran ordinateur',
          'Téléphone fixe',
          'Cartouche ink cartridge cyan',
          'Imprimante laser N&B',
        ],
      },
      {
        name: 'CANAPE/FAUTEUIL',
        gears: [
          'Canapé 2 places',
          'Canapé 3 places',
          'Canapé 4 places',
          'Fauteuil',
        ],
      },
      { name: 'CONSOMMABLE', gears: ["Bouchons d'oreilles"] },
      {
        name: 'CUISINE',
        gears: [
          'Cuillère en bois',
          'Saladier métal',
          'Couteau inox',
          'Assiettes en carton (x100)',
          'Cuillère inox',
          'Ecumoir (grand)',
          'Couteaux plastique (x100)',
          'Rape de cuisine',
          'Cuillères plastique (x100)',
          'Grand couteau cuisine',
          'Bol en carton',
          'Ouvre-boîte',
          'Fouet en métal',
          'Grand Thermos',
          'Louche',
          'Bac gastro 1/1 65mm',
          'Plateau Beurk',
          'Rouleau aluminium',
          'Touillettes (x100)',
          'Bac gastro 1/1 150mm',
          'Pichet',
          'Boule à thé inox',
          'Verre en plastique',
          'Saladier verre',
          'Fourchettes plastique (x100)',
          'Thermos 2L',
          'Planche à découper',
          'Bidon alimentaire 25L',
          'Rouleau film plastique',
          'Seau alimentaire',
          'Marmite',
          'Petite Poêle',
          'Minuteur',
          'Grands cure-dent (x100)',
          'Presse-ail',
          'Sac congelation',
          'Carafe à vin',
          'Plateau de présentation',
          'Tasse à café',
          'Assiette céramique',
          'Couteau à pain',
          'Couvercle gastro 1/1',
          'Passoires',
          'Econome',
          'Fourchette inox',
          'Gobelets en carton (x100)',
          'Verre à pied',
          'Spatule',
          'Grand saladier',
          'Petit couteau de cuisine',
          'Grande Poêle',
          'Flûtes à champagne',
          'Grosse casserole',
          'Sucrette',
          'Petite casserole',
          'Ecumoir (petit)',
          'Bol en plastique',
          'Rouleau papier cuisson',
          'Couvercle marmite',
          'Très grosse casserole',
          'Essoreuse à salade',
        ],
      },
      {
        name: 'ELECTROMENAGER',
        gears: [
          'Cuisinière',
          'Frigo + congélateur',
          'Machine à café luxelle',
          'Robot mixeur',
          'Cafetière 12 Tasses',
          'Congélateur seul',
          'Frigo + congélateur format familial',
          'Frigo de façade',
          'Percolateur 15L',
          'Plaque à induction',
          'Frigo seul',
          'Bain-marie',
          'Percolateur 6,8L',
          'Bouilloire 2L',
          'Micro-onde',
        ],
      },
      {
        name: 'LITERIE',
        gears: ['Alèse jetable', 'Drap housse', 'Matelas', 'Alèse'],
      },
      {
        name: 'MOBILIER',
        gears: [
          'Table bois pliante 1m80',
          'Coussin',
          'Chaise',
          'Support lave-main',
          'Table bois cuisine',
          'Grande table du local',
          'Table de cours 2 personnes',
          'Table basse',
          'Planche à clous',
          'Chaise de bureau',
          'Etagère en bois',
        ],
      },
      {
        name: 'PROPRETE',
        gears: [
          'Poubelle ronde 100L',
          'Sac poubelle transparent 100L',
          'Sac poubelle jaune transparent 100L',
        ],
      },
      {
        name: 'SCENE',
        gears: [
          'Jerricane gazoil',
          'Podium roulant orange',
          'Cotton à gratter (m²)',
          'Vidéoprojecteur',
        ],
      },
      {
        name: 'SECU',
        gears: [
          'BAES',
          'Cadenas pompier',
          'Chaine (grande longeur)',
          'Bâche Issue de secours',
          'Chaine (petite longueur)',
          'Plastique stationnement Interdit',
          'Cadenas',
          'Panneau rassemblement',
          'Bâche Toute sortie est définitive',
        ],
      },
      {
        name: 'TENTE',
        gears: [
          'Mur tente 4,5x3m noir',
          'Mur (3x2,5 m)',
          'Mur scène roots (10x2 m)',
          'Tente tubulaire 6x14m (tubes +toit)',
          'Mur 4x4 (4x2 m)',
          'Mur fenêtre (2x2 m)',
          'Mur 6x14 fenêtre (2x2 m)',
          'Tente ALU45 6x4m blanche',
          'Mur tente 3x3m noir',
          'Tente ALU45 6x3m blanche',
          'Porte tente 4,5x3 noire',
          'Tente tubulaire 5x8m (tubes + toit)',
          'Leste',
          'Mur tente 3x3m blanc',
          'Tente ALU45 4x4m blanche',
          'Bâche noire 2x3 mètres noire',
          'Mur 6x14 (2x6 m)',
          'Tente ALU45 4,5x3m noire',
          'Mur 5x8 (2x5 m)',
          'Porte tente 3x3m noir',
          'Tente ALU45 3x3m noire',
          'Mur 5x8 fenêtre (2x2 m)',
          'Gouttière souple 3m',
          'Porte tente 4x4 blanche',
          'Mur fenêtre (8x2 m)',
          'Tente ALU45 3x3m blanche',
          'Gouttière souple 4m',
          'Mur tente 4x4m Blanc',
          'Mur 3x3 (3x2 m)',
          'Porte tente 3x3 noire',
          'Gouttière souple 6m',
        ],
      },
    ],
  },
];
