export const signaLocations = [
  { name: '1er étage GCU' },
  { name: 'Gymnase C' },
  { name: 'Amphitéâtre Gaston Berger' },
  { name: 'Pelouse devant Colette Besson' },
  { name: 'Agora' },
  { name: 'Arche de départ des courses' },
  { name: 'Avenue des Arts' },
  { name: 'Avenue des Arts - Devant la MdE' },
  { name: 'Avenue des Arts - Devant TC' },
  { name: 'BMC' },
  { name: 'Creux GCU' },
  { name: 'SLF (sans lieu fixe)' },
  { name: 'Derrière la Grande Scène' },
  { name: 'Derrière la K-Fêt' },
  { name: 'Devant la direction' },
  { name: 'Devant la Grande Scène' },
  { name: 'Devant Laura Bassi' },
  { name: 'Devant le bâtiment des Humanités' },
  { name: 'Devant le village coureurs' },
  { name: 'Entre Jacquard et De Vinci' },
  { name: 'Entrée Nord-Est - Terrains de rugby' },
  { name: 'Entrée Nord-Ouest - CPE' },
  { name: 'Entrée Sud - INSA Einstein' },
  { name: 'Entrée Sud - Parking Double Mixte' },
  { name: 'Entrée Sud-Est - Cimetière' },
  { name: 'Entrée Sud-Ouest - Université Lyon1 / UFRAPS' },
  { name: 'Étage de la MdE' },
  { name: 'Grillon' },
  { name: 'Hall de la MdE' },
  { name: 'Mur INSA' },
  { name: 'Olivier' },
  { name: 'Parcours course à pieds' },
  { name: 'Parcours course à vélo' },
  { name: 'Parking des Humanités' },
  { name: 'Parking Eiffel' },
  { name: 'Parking Gymnase C' },
  { name: 'Patio de la MdE' },
  { name: 'Pelouse au nord de GCU' },
  { name: "Pelouse à l'est de la piscine" },
  { name: 'Pelouse des Humanités' },
  { name: 'Piscine' },
  { name: 'Rotonde' },
  { name: 'Rue des Sports' },
  { name: 'Sous-sol Gymnase C' },
  { name: 'Terrain de football synthétique' },
  { name: 'Terrain de rugby' },
  { name: 'Terrain stabilisé' },
  { name: 'Terrains de tennis derrière la piscine' },
  { name: 'Terrains de tennis devant Colette Besson' },
  { name: 'Village coureurs' },
  { name: 'Terrains de Beach Volley' },
  { name: 'Pelouse du FIMI' },
  { name: 'Derrière la direction' },
  { name: '2ème étage de GCU' },
  { name: 'Podium interplateaux' },
  { name: 'Devant le bâtiment Carnot' },
  { name: 'Travée verte' },
  { name: 'Grande Scène' },
  { name: 'Scène Roots' },
  { name: 'Chalet Backline' },
  { name: 'Espace VIP' },
  { name: 'Cave du E' },
  { name: 'Conteneur H' },
  { name: 'Local Cook' },
  { name: 'Gymnase B' },
  { name: 'Restaurant INSA' },
  { name: 'Lieu de la signa - CRL' },
  { name: 'Pierre de Fermat / Myriam Mirzakhani' },
  { name: 'Scène Nord' },
  { name: 'Derrière TC' },
  { name: 'Parking Infirmerie' },
  { name: 'Pelouse Gaston Berger' },
  { name: 'TC' },
  { name: 'Pelouse GCU' },
  { name: 'Pelouse derrière Cambridge' },
  { name: 'Pas tes oignons' },
];
