FROM node:18-alpine

WORKDIR /overbookd/api

RUN npm install -g pnpm
RUN pnpm --version
COPY pnpm-lock.yaml ./


RUN pnpm fetch

ADD ./ ./
RUN pnpm install -r --offline --filter '@overbookd/api'

RUN pnpm --filter '@overbookd/api' run build

EXPOSE 3000

CMD ["sh", "-c", "pnpm --filter '@overbookd/api' run start:dev"]
