FROM node:18-alpine

WORKDIR /overbookd
RUN chown node:node /overbookd

RUN corepack enable
RUN corepack prepare pnpm@latest-8 --activate

USER node
RUN pnpm config set store-dir .pnpm-store
RUN pnpm --version
COPY --chown=node:node pnpm-lock.yaml ./

RUN pnpm fetch

ADD --chown=node:node pnpm-workspace.yaml ./
ADD --chown=node:node package.json ./

WORKDIR /overbookd/apps/api
USER root
RUN chown node:node /overbookd/apps
RUN chown node:node /overbookd/apps/api
ADD --chown=node:node apps/api/ ./

WORKDIR /overbookd
USER node
RUN pnpm install --recursive --offline --filter '@overbookd/api'

RUN pnpm --recursive --filter '@overbookd/api' run build

EXPOSE 3000

CMD ["sh", "-c", "pnpm --recursive --filter '@overbookd/api' run start:dev"]
