FROM node:18-alpine

WORKDIR /overbookd

RUN npm install -g pnpm
RUN pnpm --version
COPY pnpm-lock.yaml ./

RUN pnpm fetch

ADD pnpm-workspace.yaml ./
ADD package.json ./

WORKDIR /overbookd/apps/api
ADD apps/api/ ./

WORKDIR /overbookd
RUN pnpm install --recursive --offline --filter '@overbookd/api'

RUN pnpm --recursive --filter '@overbookd/api' run build

EXPOSE 3000

CMD ["sh", "-c", "pnpm --recursive --filter '@overbookd/api' run start:dev"]
