include:
  - local: /.gitlab/ci/setup-pnpm.gitlab-ci.yml
  - local: /.gitlab/ci/setup-git.gitlab-ci.yml

overbookd/bump-version:
  stage: bump
  interruptible: true
  image: node:20-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $RELEASE'
    - when: never
  before_script:
    - !reference [.setup-git, script]
    - !reference [.setup-pnpm, before_script]
  script:
    - npx commit-and-tag-version
    - git push --tags ssh_origin HEAD:main
