clean-up-pipelines:
  stage: clean-up-pipelines
  image: alpine
  before_script:
    - apk update
    - apk add --update coreutils
    - apk add jq 
    - apk add curl
    - REFDATE=$(date --date="20 days ago"  '+%Y-%m-%d')
  script:
    - echo "Get pipeline before $REFDATE"
    - |
      PIPELINES=$(curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines?per_page=100&updated_before=$REFDATE" | jq '.[].id')
      for PIPELINE in $PIPELINES;
      do
          echo "Deleting pipeline $PIPELINE";
          curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines/$PIPELINE";
      done
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule") && ($PIPELINE_CLEANUP == "1")'
      when: always
    - when: never
