configurator:
  stage: configurator
  services:
    - name: docker:dind
      command: ["--experimental"]
  image: ubuntu
  before_script:
    - apt update
    - apt install curl -y
  script:
    - sh ./.gitlab/ci/configurator.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - config/config.json
    - if: '$CI_COMMIT_BRANCH == "pre-prod"'
      changes:
        - config/config.json
    - when: never
