workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME== "master"'
      variables:
        TAG: latest
        VERSION_TAG: ${cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]'}
    - if: '$CI_COMMIT_REF_NAME == "pre-prod"'
      variables:
        TAG: $CI_COMMIT_REF_NAME
        VERSION_TAG: ${CI_COMMIT_REF_NAME}_${cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]'}
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        TAG: $CI_COMMIT_REF_NAME
        VERSION_TAG: ${CI_COMMIT_REF_NAME}_${cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]'}

containerize:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  stage: docker
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker buildx create --use
    - docker buildx build --push --platform linux/amd64,linux/arm64 --tag registry.gitlab.com/24-heures-insa/overbookd/backend:$VERSION_TAG --tag registry.gitlab.com/24-heures-insa/overbookd/backend:$TAG .
  only:
    - master
    - pre-prod
    - develop
