container_scanning:
  interruptible: true
  stage: docker-scan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "pre-prod"'
      when: never
    - when: never
  before_script:
    - sudo apt update
    - sudo apt install curl -y

frontend_scan:
  extends: container_scanning
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - frontend/**/*
  needs: ["merge_requests_containerize-frontend"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "frontend/Dockerfile"
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/2705384/tags/$CI_COMMIT_SHORT_SHA"'

backend_scan:
  extends: container_scanning
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*
  needs: ["merge_requests_containerize-backend"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "backend/Dockerfile"
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/2705257/tags/$CI_COMMIT_SHORT_SHA"'
