container_scanning:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - frontend/**/*
  needs: ["merge_requests_containerize-frontend"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend:pre-prod
    DOCKERFILE_PATH: "frontend/Dockerfile"
  stage: docker-scan

backend_scan_preprod:
  extends: container_scanning
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*
  needs: ["merge_requests_containerize-backend"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/backend:pre-prod
    DOCKERFILE_PATH: "backend/Dockerfile"
