include:
  - local: /.gitlab/ci/setup-git.gitlab-ci.yml

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - !reference [.setup-git, script]
  script:
    - PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
    - TAG_DATE=$(git log -1 --pretty=format:'%ad' --date=short $CI_COMMIT_TAG)
    - CHANGELOG=$(git log $PREVIOUS_TAG...$CI_COMMIT_TAG --pretty=format:'- %s' --reverse | grep -v "chore(release)")
    - COMPARE_LINK=https://gitlab.com/24-heures-insa/overbookd-mono/-/compare/$PREVIOUS_TAG...$CI_COMMIT_TAG
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$CI_COMMIT_TAG"
    description: "## [$CI_COMMIT_TAG]($COMPARE_LINK) ($TAG_DATE)\n\n$CHANGELOG"
