include:
  - local: /.gitlab/ci/setup-git.gitlab-ci.yml

prepare_release:
  stage: install
  image: alpine
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - !reference [.setup-git, script]
  script:
    - PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
    - echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> variables.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> variables.env
    - echo "TAG_DATE=$(git log -1 --pretty=format:'%ad' --date=short $CI_COMMIT_TAG)" >> variables.env
    - echo "COMPARE_LINK=https://gitlab.com/24-heures-insa/overbookd-mono/-/compare/$PREVIOUS_TAG...$CI_COMMIT_TAG" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

publish_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_release
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - !reference [.setup-git, script]
  script:
    - echo $PREVIOUS_TAG
    - echo $CI_COMMIT_TAG
    - echo $TAG_DATE
    - echo $CHANGELOG
    - echo $COMPARE_LINK
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$CI_COMMIT_TAG"
    description: "## [$CI_COMMIT_TAG]($COMPARE_LINK) ($TAG_DATE)\n\n$(git log $PREVIOUS_TAG...$CI_COMMIT_TAG --pretty=format:'- %s' --reverse | grep -v 'chore(release)')"
