container_scanning:
  interruptible: true
  stage: docker-scan
  services:
    - name: docker:dind
      command: ["--experimental"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "pre-prod"'
      when: never
    - when: never

frontend_scan:
  extends: container_scanning
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - frontend/**/*
  needs: ["mr_frontend_publish"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "frontend/Dockerfile"

backend_scan:
  extends: container_scanning
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*
  needs: ["mr_backend_publish"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "backend/Dockerfile"
