container_scanning:
  interruptible: true
  allow_failure: false
  stage: docker-scan
  rules:
    - when: never
  before_script:
    - sudo apt update
    - sudo apt install curl -y

overbookd-web_scan:
  extends: container_scanning
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web" && $RELEASE'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - apps/web/**/*
        - package.json
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  needs: ["overbookd-web_docker_build"]
  variables:
    APP_NAME: web
    APP_PATH: apps/web
    CS_IMAGE: $CI_REGISTRY_IMAGE/$APP_NAME:${CI_COMMIT_SHORT_SHA}${CI_COMMIT_TAG}
    CS_DOCKERFILE_PATH: $APP_PATH/Dockerfile
    GIT_STRATEGY: fetch
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/4375993/tags/${CI_COMMIT_SHORT_SHA}${CI_COMMIT_TAG}"'

overbookd-api_scan:
  extends: container_scanning
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web" && $RELEASE'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - apps/api/**/*
        - package.json
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  needs: ["overbookd-api_docker_build"]
  variables:
    APP_NAME: api
    APP_PATH: apps/api
    CS_IMAGE: $CI_REGISTRY_IMAGE/$APP_NAME:${CI_COMMIT_SHORT_SHA}${CI_COMMIT_TAG}
    CS_DOCKERFILE_PATH: $APP_PATH/Dockerfile
    GIT_STRATEGY: fetch
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/4375990/tags/${CI_COMMIT_SHORT_SHA}${CI_COMMIT_TAG}"'
