container_scanning:
  interruptible: true
  stage: docker-scan
  rules:
    - when: never
  before_script:
    - sudo apt update
    - sudo apt install curl -y

frontend_scan:
  extends: container_scanning
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - frontend/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - frontend/**/*
  needs: ["preprod_frontend_docker_build"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "frontend/Dockerfile"
    SCOPE: frontend
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/2685416/tags/$CI_COMMIT_SHORT_SHA"'

backend_scan:
  extends: container_scanning
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - backend/**/*
  needs: ["backend_docker_build"]
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "backend/Dockerfile"
    SCOPE: backend
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" --request "DELETE" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/2685488/tags/$CI_COMMIT_SHORT_SHA"'
