merge_requests_containerize-backend:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  stage: mr-docker-backend
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/amd64,linux/arm64 ./backend
  only:
    changes:
      - backend/*
    refs:
      - merge_requests
