npm-publish:
  stage: npm-publish
  extends: .setup-pnpm
  image: node:24.21.0-alpine
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $RELEASE'
    - when: never
  script:
    - echo "@overbookd:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - CURRENT_VERSION=$(pnpm --filter "${PNPM_WORKSPACE}" exec node -p "require('./package.json').version")
    - |
      if pnpm view "${PNPM_WORKSPACE}@${CURRENT_VERSION}" version > /dev/null 2>&1; then
        echo "${PNPM_WORKSPACE}@${CURRENT_VERSION} already published, skipping"
        exit 0
      fi
    - pnpm i --filter "${PNPM_WORKSPACE}..."
    - pnpm --filter "${PNPM_WORKSPACE}" run build:ci
    - pnpm --filter "${PNPM_WORKSPACE}" publish --no-git-checks
parallel:
  matrix:
    - PNPM_WORKSPACE: "@overbookd/csv"
    - PNPM_WORKSPACE: "@overbookd/slugify"
